server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: authuser
    password: authpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: PROD_SECRET_KEY
  expiration: 3600000
