spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: authuser
    password: authpass
    driver-class-name: org.postgresql.Driver

features:
  user-registration: true
  refresh-token-enabled: true

security:
  jwt:
    access-expiration: 900000
    refresh-expiration: 604800000

observability:
  security-logs: true
  metrics-enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://jaeger:4317

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
