spring:
  datasource:
    url: jdbc:postgresql://prod-db:5432/authdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

features:
  user-registration: false

security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: 600000
    refresh-expiration: 259200000

observability:
  security-logs: true
  metrics-enabled: true
